import Head from 'next/head';

import Layout from '../components/UI/Layout';
import Featured from '../components/UI/Featured';
import Categories from '../components/UI/Categories';

export default function Home({ categories }) {
  const { data } = categories;

  return (
    <div className="app">
      <Head>
        <title>Ecommerce Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Featured />
        <Categories categories={data} />
      </Layout>
    </div>
  );
}

export async function getServerSideProps() {
  const res = await fetch('http://localhost:3000/api/categories');
  const categories = await res.json();

  return {
    props: { categories },
  };
}
