import Head from 'next/head';

import Header from '../components/UI/Header';

export default function Home() {
  return (
    <div className="app">
      <Head>
        <title>Ecommerce Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
    </div>
  );
}
