import Head from 'next/head';

import Layout from '../components/UI/Layout';
import Featured from '../components/UI/Featured';
import Categories from '../components/UI/Categories';

export default function Home() {
  return (
    <div className="app">
      <Head>
        <title>Ecommerce Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Featured />
        <Categories />
      </Layout>
    </div>
  );
}
