import Head from 'next/head';

import Header from '../components/UI/Header';
import Featured from '../components/UI/Featured';
import Categories from '../components/UI/Categories';

export default function Home() {
  return (
    <div className="app">
      <Head>
        <title>Ecommerce Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Featured />
      <Categories />
    </div>
  );
}
